### ISSUE TITLE
ngModel doesn't fully work

### ISSUE THREAD

**Issue by charleshimmer** [tinymce/tinymce-angular#73] opened 2019-02-22 14:41 UTC
I'm noticing two cases in which [(ngModel)] isn't acting like you would expect. I'm using angular version 7, tinymce-angular version 3.0.0, and tinymce 5.0

1) ngModel is updating my variable when there is a text change. But when I bold some text, or create a hyperlink, ngModel is not firing / updating my variable.  Seems like any toolbar button actions are not updating the ngModel even though the value has changed. 

2) when I update the variable bound to the ngModel the editor does not update.  This is suppose to be a two way binding so I expect any changes to the variable to update the value of the editor but it isn't.

**Comment by charleshimmer** [comment] 2019-02-22 15:39
After reading the source code I think I have hacked a solution by using ViewChild and the `writeValue` and `registerOnChange` methods. This is def less than ideal as it requires using undocumented methods and a lot more code just to accomplish with ngModel should do.

**Comment by fyrkant** [comment] 2019-02-25 09:31
I'm not able to reproduce this, the ngModel seems to update as it should in my testing. Can you create a small app that reproduces the problem that I can take a look at?

**Comment by charleshimmer** [comment] 2019-02-25 14:03
I found if I added an event handler for both `ngModel` AND `ngModelChanges` I could get it to fire. Does your test possible test both of those at the same time?  

What about the second issue above? If you don't add any more characters, but just modify the styles of the content in the editor (like bold some text) does ngModel fire for you? I've found I had to use `registerOnChange` if I want an up to date representation of the editor's content.

**Comment by ThomasPe** [comment] 2019-05-03 14:17
Any news on this? I'm using node.replaceWith() directly in the editor but I'm struggling getting the update value back into my ngModel.

**Comment by SimonFc** [comment] 2019-05-20 13:49
@ThomasPe Are you replacing the content of a node inside Tiny's editable area directly? If that's the case there's nothing we can do about it. I don't think that Angulars implementation with ngModel with native input elements cover that case either.

As a work arround - you could simple create a new [undo-level](https://www.tiny.cloud/docs/api/tinymce/tinymce.undomanager/#add) which will fire the change event which, in turn, tinymce-angular listens to. Let me know if you got any questions!

@charleshimmer I'm not able to reproduce the original issue either. ngModel updates when I bold or create a hyperlink. Two-way binding is working for me as well. I'll be closing this issue now but let me know if you are able to reproduce it!

**Closed by SimonFc** 2019-05-20 13:49 UTC
Labels: question
