### ISSUE TITLE
unable to webpack with env.prod

### ISSUE THREAD

**Issue by Trapulo** [tinymce/tinymce-angular#10] opened 2018-04-17 13:52 UTC
Hi,
I'm using the module in an angular project managed with webpack.
All ok in development mode, but if I try to webpack with env.prod I have this error:

 ERROR in @tinymce\tinymce-angular\tinymce-tinymce-angular.ts(7,2): Error during template compile of 'EditorModule'
      Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
        'NgModule' calls 'ɵmakeDecorator'.

any idea?
thanks

"tinymce": "^4.7.11",
"@tinymce/tinymce-angular": "^1.0.7"
"webpack": "^3.10.0"
  "typescript": "2.6.2"

**Comment by fyrkant** [comment] 2018-04-23 02:44
Do you have a repo with your code that I can take a look at?

**Comment by Trapulo** [comment] 2018-04-23 15:24
I reverted something in my project to solve other compatibility problems, and currently webpack env is not reporting that error.

My current versions are now:
    "tinymce": "^4.7.11",
 "@tinymce/tinymce-angular": "1.0.5",
 "webpack": "^3.10.0"
 "typescript": "2.6.2",

However I've still an other compiler error (not related to this project) that currently I cannot solve. I don't know if this is hiding the tinymce-angular's one, or if reverting to 1.0.5 has "solved" it.

**Comment by fyrkant** [comment] 2018-04-26 00:29
I don't think I've changed anything that should cause that compilation error in the latest versions. 🤔 

I'll close this because I couldn't reproduce it, but come back and leave a comment if you can make a simple repo with a reproduction.

**Closed by fyrkant** 2018-04-26 00:29 UTC
