### ISSUE TITLE
Editor is unusable after initial rendering

### ISSUE THREAD

**Issue by CodingGorilla** [tinymce/tinymce-angular#11] opened 2018-04-24 19:38 UTC
I have an issue that seems similar to #9, where the first time the editor is displayed it works fine, but in subsequent uses most of the editor is visible (the toolbars and menus are visible) but the body of the editor is not visible nor editable.  From what I can see the `iframe` element is being rendered into the view, but what I notice is that the `body` element inside of the iframe is not initialized (for a lack of a better description) in the same way the 2nd time around.  The second time the editor is displayed, the body element is completely bare, just: `<body><body>` with no content or attributes.

This editor is contained within a kendo ui dialog component, and it's when the dialog is dismissed and then displayed again that it breaks.

**Comment by fyrkant** [comment] 2018-04-25 01:43
Yep I'd say this is a duplicate of #9.

**Closed** 2018-04-25 01:45 UTC
