### ISSUE TITLE
When using tinymce editor in matDialog, it doesnot seems to load the js always.

### ISSUE THREAD

**Issue by amitmoondra** [tinymce/tinymce-angular#99] opened 2019-07-24 11:01 UTC
For the first time the js is loaded and then after sometime its gone.
Cant figure out why is that happening.
Also couldnot figure out how to remove the editor that i see is the answer, but while using the angular wrapper module that tinymce-angular i dont see how that can be achieved.
Need a solution.

**Comment by SimonFc** [comment] 2019-07-24 11:08
I think this issue is the same as the one this [PR](https://github.com/tinymce/tinymce-angular/pull/97) is trying to solve. I'm looking into possible ways to fix this now.

Just to confirm that your issue is the same, could you set up a minimal reproduction on [codesandbox](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14)?

**Comment by amitmoondra** [comment] 2019-07-24 11:16
> I think this issue is the same as the one this [PR](https://github.com/tinymce/tinymce-angular/pull/97) is trying to solve. I'm looking into possible ways to fix this now. Just to confirm that your issue is the same, could you set up a minimal reproduction app on [codesandbox](https://codesandbox.io/s/6zlmmkkk1n?fontsize=14)?

**Comment by amitmoondra** [comment] 2019-07-24 11:16
will do that

**Comment by amitmoondra** [comment] 2019-07-24 12:54
it works in sandbox, dont know some issues on my local, but it seems this is an issue

**Comment by jscasca** [comment] 2020-07-07 05:09
Hey @amitmoondra 

Sorry it took so long to get to this, is it still an issue?

**Comment by tinydylan** [comment] 2020-09-16 13:41
@amitmoondra - Since the issue doesn't occur on sandbox, but does occur on your local environment, are you able to please provide a simple self-contained example demonstrating the issue? We'll then be able to look into it further.

I'll close the issue for now, but feel free to re-open if the issue still occurs.

Thanks

**Closed by tinydylan** 2020-09-16 13:41 UTC
