### ISSUE TITLE
TS-996002 error when using ivy compiler

### ISSUE THREAD

**Issue by LuisSarmientoM** [tinymce/tinymce-angular#109] opened 2019-08-28 00:58 UTC
**Description**
I'm using the ivy compiler and when I use ng build --prod or ng serve --prod the compiler gives me the following error

![image](https://user-images.githubusercontent.com/42702720/63817881-f096a480-c903-11e9-86eb-dbb1a8f3949a.png)

this error refers to the file that I import into my module and only comes out when I compile in production mode

**Comment by SimonFc** [comment] 2019-08-28 08:26
Seems like it could be an issue with the metadata we're generating for this package

**Comment by LuisSarmientoM** [comment] 2019-08-30 16:19
How do I fix this?

**Comment by SimonFc** [comment] 2019-09-02 08:16
@LuisSarmientoM  I haven't had time to look into this yet but will probably do so in the next 2-3 weeks(unless someone else knows what the issue is)

**Comment by LuisSarmientoM** [comment] 2019-09-02 15:20
Okay, thanks. I'll keep using the regular compiler for now.

**Comment by SimonFc** [comment] 2019-09-23 11:27
@LuisSarmientoM  We have a new version released with a fix for this, 3.3.1. I'll close this now but let me know if you encounter any further issues!

**Closed by SimonFc** 2019-09-23 11:27 UTC
Labels: status: escalated
