### ISSUE TITLE
formControlName only working first time

### ISSUE THREAD

**Issue by josevavia** [tinymce/tinymce-angular#128] opened 2020-01-15 02:21 UTC
Using angular8+ionic4, I have a components with a dynamic form created using Reactive Forms. I have an array of fields and types, and depending on the type I create a different html control (input, calendar, number or tinymce). 

When "type" is "tinymce", I want to create a tinymce, so:
*Note the extra "textarea" element, it is there for testing purpuses

my page.html
```
<editor [formControlName]='param.model' [init]='optionsTinymce' *ngIf="param.type == 'tiny'"></editor>
<textarea [formControlName]="param.model" *ngIf="param.type == 'tiny'"></textarea>
```

my page.ts
```
[...]
  optionsTinymce = {
    toolbar: 'undo redo | bold italic underline | fullscreen',
    menubar: false,
    statusbar: false,
    base_url: '/tinymce',
    suffix: '.min',
    plugins: 'autoresize fullscreen',
    // height : 450,
  };

[....]
this.form.addControl(param.model, new FormControl(value));
```

First time I load the page I can see both tinymce and normal textarea, with correct values from my model:
![image](https://user-images.githubusercontent.com/2239846/72399086-654c6d00-3745-11ea-843a-7510f3676b2d.png)

The problem is, when I navigate to any other page or go back, when I go to any other page with a tinymce editor, the editor is empty (but the textarea is still working correctly):
![image](https://user-images.githubusercontent.com/2239846/72399117-75644c80-3745-11ea-985a-08ebe4cccb40.png)

I tried different solutions as indicated in https://github.com/tinymce/tinymce-angular/blob/master/stories/materialtabs/MaterialTabs.component.ts, using changedetectorcf... but nothings works.

My setup:
"@tinymce/tinymce-angular": "^3.3.1",
"tinymce": "^5.1.5",
 Ionic Framework               : @ionic/angular 4.4.1

**Comment by SimonFc** [comment] 2020-01-15 08:46
Is TinyMCE still functional or is the issue just that you lose the content?

Assuming that the issue is that TinyMCE break, taking a look at [this](https://github.com/tinymce/tinymce-angular/blob/master/stories/transclusion/Transclusion.component.ts) example might be beneficial. (Using this approach it's possible to conditionally show TinyMCE without tearing it down)

**Comment by josevavia** [comment] 2020-01-15 09:37
I checked that TinyMCE es enterily break, I will try your example using transclusion

Thank for your response.

**Comment by josevavia** [comment] 2020-01-16 11:31
Thanks again.

Based in the example, finally I resolved the problem with a container with *ngIf:
```
<ng-container *ngIf="param.type == 'tiny' && showTinys">
     <editor class="noselect" [formControlName]='param.model' [init]='optionsTinymce'></editor>
</ng-container>
```

In the .ts file, `showTinys` has a `false` default value, and when everything was loaded and configured, I set `this.showTinys = true` and everything works.

It seems that surrounding the element in a container with a *ngIf "switch" reloads the Tinymce component.

**Comment by SimonFc** [comment] 2020-01-16 13:02
Ah okay great!, it looks like you ended up with a solution similar to the Material Tabs example we provide.

I think I can fairly confidently say that the issue you encountered is due to how Angular can remove components from the DOM without tearing them down. For most things this is alright but not with iframes. Whenever an iframe is moved or detached from the DOM it'll re-render (this is just native iframe behavior). Since TinyMCE is using an iframe it'll will break whenever it's detached without properly tearing it down. Usage of `*ngIf` seems to make Angular actually tear everything down via the `ngOnDestroy` hook, thus solving the problem.

I'll close this since you found a solution!

**Closed by SimonFc** 2020-01-16 13:02 UTC
