### ISSUE TITLE
TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by Shustoff** [tinymce/tinymce-angular#76] opened 2019-03-14 13:18 UTC
I have some problem: if insert tinymce-angular component `<editor>` in angular material `<mat-tab>` component, then navigation on tabs triggers an error: 
```javascript
ERROR TypeError: Cannot read property 'open' of undefined
    at Object.initContentBody (tinymce.js:22989)
    at Object.init$1 [as init] (tinymce.js:23160)
    at Object.init$2 [as init] (tinymce.js:23440)
    at Editor.<anonymous> (tinymce.js:23526)
    at Array.<anonymous> (tinymce.js:6752)
    at each$1 (tinymce.js:2125)
    at loadScripts (tinymce.js:6749)
    at ScriptLoader.loadScripts (tinymce.js:6762)
    at ScriptLoader.loadQueue (tinymce.js:6699)
    at tinymce.js:23524
```

**Comment by SimonFc** [comment] 2019-03-22 12:12
I'm guessing it's because the editor gets removed improperly when you switch tab. Try using [remove](https://www.tiny.cloud/docs/api/tinymce/tinymce.editormanager/#remove) to properly tear down the editor instance.
Let me know if the issue remains!

**Comment by chihab** [comment] 2019-03-31 09:59
The editor component does't work when inside a template "controlled" by a structural directive (*ngIf, *ngFor, *ngTemplateOutlet...)

This code works fine:
```html
<editor
      [id]="'tips'"
      [name]="'tips'"
      [(ngModel)]="text"
      [init]="editorSettings">
 </editor>
```

This code doesn't
```html
<ng-template #editor>
    <editor
      [id]="'tips'"
      [name]="'tips'"
      [(ngModel)]="text"
      [init]="editorSettings">
    </editor>
</ng-template>
<ng-container *ngTemplateOutlet="editor"></ng-container>
```

**Comment by lidibe** [comment] 2019-04-16 21:13
Team,

Any update on the above mentioned issue?

I am facing the same challenge.

L

**Comment by SimonFc** [comment] 2019-04-17 08:47
Hi,
It appears that this is because when the mat-tab component is bootstrapped all the subcomponents are being bootstrapped as well in a detached state. That is, they're not being mounted in the document. This is causing some issues for Tiny since it requires the document on init. Seems like this has been causing [issues](https://github.com/angular/angular/issues/13921) for more people, especially for third-party libraries.

The best solution for this would be to make the tinymce-angular wrapper smarter and delay the setup and is something we'll be looking into. Luckily there're some possible workarounds for the issue though [workaround](https://stackblitz.com/edit/angular-9uvqzk?file=src%2Fapp%2Fapp.component.ts) for this issue.

**Comment by SimonFc** [comment] 2019-04-17 14:36
I've been diving deeper into this issue and unfortunately, we won't be able to provide a fix for this.

The problem consists of two parts. The first of delaying initial setup as I mentioned in my previous comment is something we could do, although there's a second issue which would render that insufficient. The TinyMCE editor works with an iframe and whenever that iframe is moved within its owner-document, let alone detached, its content will re-render. This will happen on tab change with Angular-material since the whole tinymce-angular component will be detached from the DOM.

Even if we were to save the editor's content and reset it manually we would lose the iframe documents state(current selection etc.) due to it rerendering as well. This is a native iframe behavior and something which we have no control over.

(Gecko)[https://bugzilla.mozilla.org/show_bug.cgi?id=254144] and (WebKit)[https://bugs.webkit.org/show_bug.cgi?id=13574#c10] issues.

**Closed by SimonFc** 2019-04-17 14:36 UTC

**Comment by jbjhjm** [comment] 2019-09-19 09:43
There's a simple solution for the first of the two issues (component is initialized before being attached to DOM), which does not require external inputs or checks.

```ts
@Component({
	...
})
export class UiEditorComponent extends EditorComponent {
	private _elementRef2:ElementRef;
	
	constructor(elementRef: ElementRef, ngZone: NgZone, @Inject(PLATFORM_ID) platformId: Object) {
		super(elementRef,ngZone,platformId);
		// this.elementRef is private. Need a duplicate
		this._elementRef2 = elementRef;
	}

	checkDomAttachment():boolean {
		// check if component has been attached to DOM yet
		return document.body.contains(this._elementRef2.nativeElement);
	}
	
	public initialise() {
		if(!this._elementRef2 || !this.checkDomAttachment()) {
			// component is not in DOM. Try again in 100 ms.
			setTimeout(()=>{
				this.initialise();
			},100)
			return;
		}
		super.initialise();
	}

}
```

**Comment by rcanu** [comment] 2019-09-26 15:33
Have you guys tried wrapping `<editor>` with `<ng-template matTabContent></ng-template>`? This worked for me.

**Comment by HelenReis** [comment] 2019-12-11 20:42
I've tried some workings here, but that doesn't worked for me.
A solution for me was:
Setting my configuration init of the editor on lifecycle OnInit
Wrapping the editor component  with some variable that only is true when passed for ngAfterViewInit
Setting my configuration init null on OnDestroy

Something like on .html:

`<form [formGroup]="this.form">
    <div *ngIf="this.inicializado" fxLayout="row" fxFlex="100" class="w-100-p m-36">
        <editor [init]="this.configuracoesEditor" formControlName="template" class="w-100-p"> 
       </editor>
    </div>
</form>`

On .ts:

    `public configuracoesEditor: object;
    public form: FormGroup;
    public inicializado: boolean;

    ngOnInit(): void {
        this.form = this._formBuilder.group({
            template: ['', []]
        });
        this.configuracoesEditor = configuracaoPadraoEditor(false, false, '285px');
    }

    ngAfterViewInit(): void {
        // you can setTimeOut if display some message on your console
        this.inicializado = true;
    }

    ngOnDestroy(): void {
        this.configuracoesEditor = null;
    }`

**Comment by sjahongir** [comment] 2020-07-07 01:13
> Have you guys tried wrapping `<editor>` with `<ng-template matTabContent></ng-template>`? This worked for me.

Worked for me also! Thanks!

**Comment by leomayer** [comment] 2020-07-14 09:51
> Have you guys tried wrapping `<editor>` with `<ng-template matTabContent></ng-template>`? This worked for me.

This worked for me - **BUT** only when I wrapped the complete content of the `mat-tab`, i.e. 
```
<mat-tab>
    <ng-template matTabContent> 
         <span>My quick test</span>
         <editor ...
    </ng-template> 
</mat-tab>
```

**Comment by xeleoss** [comment] 2020-10-02 15:02
Is there any way to solve the problem without tamplate? I'm not comfortable using it

**Comment by andreElrico** [comment] 2021-05-19 09:48
here is a minimal reproducible example of the bug:

https://stackblitz.com/edit/test-contentprojection-fgg4xy?file=src%2Fapp%2Fapp.component.ts

So here is an explanation of the issue:

when we project <editor></editor> into a component (eg. <child>) and inside of <child>'s template the content (<editor>) is not DIRECTLY rendered/ evaluated the issue occurs.

This could be because
+ we use ContentChild/ren and render this content "later" in time. Could be because <editor> is in an inactive tab.
+ Our <ng-content> is inside a ng-template that is not rendered directly.

The reason behind this is that <editor> is "initialized" (because it belongs to <parents>'s template/view (the host containing <child> and <editor>) ) but it NOT rendered to DOM yet.
Initlialized means that the tinymce.js script is also "evoked". Tinymce.js will not find any Dom-element it will use as anchor for its editor.

So the only solution to this is to project <editor> inside of a <ng-template> and let the <child> decide when to render and initialize it.

**Comment by aeslinger0** [comment] 2022-09-25 16:57
In my case, TinyMCE was being projected into an `ng-content` inside of `mat-tab`. Wrapping it in `<ng-template matTabContent></ng-template>` didn't work for me because according to the documentation on [Conditional content projection](https://angular.io/guide/content-projection#conditional-content-projection), "Using an [<ng-content>](https://angular.io/api/core/ng-content) element in these cases is not recommended, because when the consumer of a component supplies the content, that content is always initialized, even if the component does not define an [<ng-content>](https://angular.io/api/core/ng-content) element or if that [<ng-content>](https://angular.io/api/core/ng-content) element is inside of an [ngIf](https://angular.io/api/common/NgIf) statement."

So I had to abandon the use of `ng-content` and do it this way:

1. Change code wrapping the content to be projected from `<ng-container details>...</ng-container>` to `<ng-template #details>...</ng-template>`.
2. In the component where the content was to be projected to, add a reference to this named template: `@ContentChild('details') details!: TemplateRef<unknown>;`
3. Display the content using ngTemplateOutlet instead of `<ng-content select="[details]"></ng-content>`. For tabs with the editor that were not going to be displayed right away, wrap the outlet in a conditional statement:

                <mat-tab>
                    <ng-template mat-tab-label>
                        <mat-icon>description</mat-icon>
                        <span class="tab-icon-text">Details</span>
                    </ng-template>
                    <ng-template matTabContent>
                        <ng-container *ngIf="tabsReady.get(2)">
                            <ng-container [ngTemplateOutlet]="details"></ng-container>
                        </ng-container>
                    </ng-template>
                </mat-tab>

4. Set when the tab has been switched to:
html:

        <mat-tab-group (selectedIndexChange)="tabChanged($event)" ...

typescript:

        tabsReady = new Map<number, boolean>();

        tabChanged(tabIndex: number) {
            this.tabsReady.set(tabIndex, true);
        }
